# Generated by Django 4.2.1 on 2023-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='avatar',
            new_name='author_avatar',
        ),
        migrations.AddField(
            model_name='commit',
            name='committer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_repository'),
        ),
    ]
